### ISSUE TITLE
Support pull requests

### ISSUE THREAD

**Issue by Gskartwii** [ValkyrieRBXL/Valkyrie_CI#4]

**Comment by eLunate** [comment]
What's this looking to do?

**Comment by Gskartwii** [comment]
It's meant to build the module when a pull request is issued or updated, so that contributors can test their changes.

**Comment by eLunate** [comment]
Does Github have web hooks for that?

**Comment by Gskartwii** [comment]
[Yeah](https://developer.github.com/webhooks)

**Comment by eLunate** [comment]
Alrighty

**Comment by Gskartwii** [comment]
Done.
